use atgpvt;

select * FROM EMPLOYEE;
SELECT * FROM BRANCH;

SELECT  EMPLOYEE.EMP_ID,EMPLOYEE.ENAME,EMPLOYEE.JOB_DESC,BRANCH.BR_NAME
FROM EMPLOYEE
INNER JOIN BRANCH
ON EMPLOYEE.BRANCH_ID = BRANCH.BRANCH_ID
ORDER BY EMP_ID;

CREATE VIEW EMP_NAME
AS
SELECT EMPLOYEE.EMP_ID ,EMPLOYEE.ENAME,EMPLOYEE.JOB_DESC,BRANCH.BR_NAME
FROM EMPLOYEE
INNER JOIN BRANCH
ON EMPLOYEE.BRANCH_ID = BRANCH.BRANCH_ID
ORDER BY EMP_ID;

select * FROM EMP_BR
WHERE JOB_DESC = "ADMIN";

--- DROP VIEW EMP_BR



